// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwWPYT3-mfo2mtNc5vMQLRZqgC09T681Q',
    appId: '1:752107645094:web:a17eedf908b83db2012c67',
    messagingSenderId: '752107645094',
    projectId: 'cs-swrv',
    authDomain: 'cs-swrv.firebaseapp.com',
    storageBucket: 'cs-swrv.appspot.com',
    measurementId: 'G-RBJF5TX7X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE2I254Gc8jUjzOSla4ECe9VcuqjAcpuo',
    appId: '1:752107645094:android:f86c62d0613a962f012c67',
    messagingSenderId: '752107645094',
    projectId: 'cs-swrv',
    storageBucket: 'cs-swrv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR_nfCYqPZXYI9WFEFzsV1IqWVcUzPXPc',
    appId: '1:752107645094:ios:23f22607964585b6012c67',
    messagingSenderId: '752107645094',
    projectId: 'cs-swrv',
    storageBucket: 'cs-swrv.appspot.com',
    iosClientId: '752107645094-e6iesugkv4igj6sul9ncq71865vsasvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.swrv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR_nfCYqPZXYI9WFEFzsV1IqWVcUzPXPc',
    appId: '1:752107645094:ios:23f22607964585b6012c67',
    messagingSenderId: '752107645094',
    projectId: 'cs-swrv',
    storageBucket: 'cs-swrv.appspot.com',
    iosClientId: '752107645094-e6iesugkv4igj6sul9ncq71865vsasvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.swrv',
  );
}
